from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ConstellationNameInfo:
    japanese_name: str
    latin_name: str


CONSTELLATION_NAME_MAP: dict[str, ConstellationNameInfo] = {
    "And": ConstellationNameInfo("アンドロメダ座", "Andromeda"),
    "Ant": ConstellationNameInfo("ポンプ座", "Antlia"),
    "Aps": ConstellationNameInfo("ふうちょう座", "Apus"),
    "Aql": ConstellationNameInfo("わし座", "Aquila"),
    "Aqr": ConstellationNameInfo("みずがめ座", "Aquarius"),
    "Ara": ConstellationNameInfo("さいだん座", "Ara"),
    "Ari": ConstellationNameInfo("おひつじ座", "Aries"),
    "Aur": ConstellationNameInfo("ぎょしゃ座", "Auriga"),
    "Boo": ConstellationNameInfo("うしかい座", "Bootes"),
    "Cae": ConstellationNameInfo("ちょうこくぐ座", "Caelum"),
    "Cam": ConstellationNameInfo("きりん座", "Camelopardalis"),
    "Cap": ConstellationNameInfo("やぎ座", "Capricornus"),
    "Car": ConstellationNameInfo("りゅうこつ座", "Carina"),
    "Cas": ConstellationNameInfo("カシオペヤ座", "Cassiopeia"),
    "Cen": ConstellationNameInfo("ケンタウルス座", "Centaurus"),
    "Cep": ConstellationNameInfo("ケフェウス座", "Cepheus"),
    "Cet": ConstellationNameInfo("くじら座", "Cetus"),
    "Cha": ConstellationNameInfo("カメレオン座", "Chamaeleon"),
    "Cir": ConstellationNameInfo("コンパス座", "Circinus"),
    "CMa": ConstellationNameInfo("おおいぬ座", "Canis Major"),
    "CMi": ConstellationNameInfo("こいぬ座", "Canis Minor"),
    "Cnc": ConstellationNameInfo("かに座", "Cancer"),
    "Col": ConstellationNameInfo("はと座", "Columba"),
    "Com": ConstellationNameInfo("かみのけ座", "Coma Berenices"),
    "CrA": ConstellationNameInfo("みなみのかんむり座", "Corona Australis",),
    "CrB": ConstellationNameInfo("かんむり座", "Corona Borealis",),
    "Crt": ConstellationNameInfo("コップ座", "Crater"),
    "Cru": ConstellationNameInfo("みなみじゅうじ座", "Crux"),
    "Crv": ConstellationNameInfo("からす座", "Corvus"),
    "CVn": ConstellationNameInfo("りょうけん座", "Canes Venatici"),
    "Cyg": ConstellationNameInfo("はくちょう座", "Cygnus"),
    "Del": ConstellationNameInfo("いるか座", "Delphinus"),
    "Dor": ConstellationNameInfo("かじき座", "Dorado"),
    "Dra": ConstellationNameInfo("りゅう座", "Draco"),
    "Equ": ConstellationNameInfo("こうま座", "Equuleus"),
    "Eri": ConstellationNameInfo("エリダヌス座", "Eridanus"),
    "For": ConstellationNameInfo("ろ座", "Fornax"),
    "Gem": ConstellationNameInfo("ふたご座", "Gemini"),
    "Gru": ConstellationNameInfo("つる座", "Grus"),
    "Her": ConstellationNameInfo("ヘルクレス座", "Hercules"),
    "Hor": ConstellationNameInfo("とけい座", "Horologium"),
    "Hya": ConstellationNameInfo("うみへび座", "Hydra"),
    "Hyi": ConstellationNameInfo("みずへび座", "Hydrus"),
    "Ind": ConstellationNameInfo("インディアン座", "Indus"),
    "Lac": ConstellationNameInfo("とかげ座", "Lacerta"),
    "Leo": ConstellationNameInfo("しし座", "Leo"),
    "Lep": ConstellationNameInfo("うさぎ座", "Lepus"),
    "Lib": ConstellationNameInfo("てんびん座", "Libra"),
    "LMi": ConstellationNameInfo("こじし座", "Leo Minor"),
    "Lup": ConstellationNameInfo("おおかみ座", "Lupus"),
    "Lyn": ConstellationNameInfo("やまねこ座", "Lynx"),
    "Lyr": ConstellationNameInfo("こと座", "Lyra"),
    "Men": ConstellationNameInfo("テーブルさん座", "Mensa"),
    "Mic": ConstellationNameInfo("けんびきょう座", "Microscopium"),
    "Mon": ConstellationNameInfo("いっかくじゅう座", "Monoceros"),
    "Mus": ConstellationNameInfo("はえ座", "Musca"),
    "Nor": ConstellationNameInfo("じょうぎ座", "Norma"),
    "Oct": ConstellationNameInfo("はちぶんぎ座", "Octans"),
    "Oph": ConstellationNameInfo("へびつかい座", "Ophiuchus"),
    "Ori": ConstellationNameInfo("オリオン座", "Orion"),
    "Pav": ConstellationNameInfo("くじゃく座", "Pavo"),
    "Peg": ConstellationNameInfo("ペガスス座", "Pegasus"),
    "Per": ConstellationNameInfo("ペルセウス座", "Perseus"),
    "Phe": ConstellationNameInfo("ほうおう座", "Phoenix"),
    "Pic": ConstellationNameInfo("がか座", "Pictor"),
    "PsA": ConstellationNameInfo("みなみのうお座", "Piscis Austrinus",),
    "Psc": ConstellationNameInfo("うお座", "Pisces"),
    "Pup": ConstellationNameInfo("とも座", "Puppis"),
    "Pyx": ConstellationNameInfo("らしんばん座", "Pyxis"),
    "Ret": ConstellationNameInfo("レチクル座", "Reticulum"),
    "Scl": ConstellationNameInfo("ちょうこくしつ座", "Sculptor"),
    "Sco": ConstellationNameInfo("さそり座", "Scorpius"),
    "Sct": ConstellationNameInfo("たて座", "Scutum"),
    "Ser": ConstellationNameInfo("へび座", "Serpens"),
    "Sex": ConstellationNameInfo("ろくぶんぎ座", "Sextans"),
    "Sge": ConstellationNameInfo("や座", "Sagitta"),
    "Sgr": ConstellationNameInfo("いて座", "Sagittarius"),
    "Tau": ConstellationNameInfo("おうし座", "Taurus"),
    "Tel": ConstellationNameInfo("ぼうえんきょう座", "Telescopium"),
    "TrA": ConstellationNameInfo("みなみのさんかく座", "Triangulum Australe"),
    "Tri": ConstellationNameInfo("さんかく座", "Triangulum"),
    "Tuc": ConstellationNameInfo("きょしちょう座", "Tucana"),
    "UMa": ConstellationNameInfo("おおぐま座", "Ursa Major"),
    "UMi": ConstellationNameInfo("こぐま座", "Ursa Minor"),
    "Vel": ConstellationNameInfo("ほ座", "Vela"),
    "Vir": ConstellationNameInfo("おとめ座", "Virgo"),
    "Vol": ConstellationNameInfo("とびうお座", "Volans"),
    "Vul": ConstellationNameInfo("こぎつね座", "Vulpecula"),
}